### ISSUE TITLE
PHPUnit 6 support?

### ISSUE THREAD

**Issue by GaryJones** [php-vcr/phpunit-testlistener-vcr#20]
Are there plans to support PHPUnit 6? The PHPUnit code is now [namespaced](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0).

**Comment by allejo** [comment]
In the mean time, aliasing the classes in my test `bootstrap.php` works:

```php
$phpunitAliases = [
    '\PHPUnit\Framework\Test' => '\PHPUnit_Framework_Test',
    '\PHPUnit\Framework\TestListener' => '\PHPUnit_Framework_TestListener',
    '\PHPUnit\Framework\Warning' => '\PHPUnit_Framework_Warning',
    '\PHPUnit\Framework\AssertionFailedError' => '\PHPUnit_Framework_AssertionFailedError',
    '\PHPUnit\Framework\TestSuite' => '\PHPUnit_Framework_TestSuite',
];

foreach ($phpunitAliases as $namespaced => $alias) {
    if (!class_exists($alias)) {
        class_alias($namespaced, $alias);
    }
}
```

**Comment by dborsatto** [comment]
The problem with aliasing is that if other packages you have installed require on PHPUnit 6, installation will fail because of conflicting requirements 🙁
