### ISSUE TITLE
PHP 7.4 Support?

### ISSUE THREAD

**Issue by nrobates** [php-vcr/phpunit-testlistener-vcr#36]
Is there any plans to having this package support PHP 7.4? We just did an upgrade and all of our tests now fail as a result of using the listener.

**Comment by JeroenVanOort** [comment]
I've only recently taken over maintainership of PHP-VCR and don't have the time to look into this myself. However you're very much welcome to work on this yourself and submit a PR.

**Comment by raisonon** [comment]
How do the tests fail?

**Comment by nrobates** [comment]
I believe this is already fixed. For some reason, I completely forgot this ticket existed. Closing as I don't have the issue any further.
