### ISSUE TITLE
Create new version

### ISSUE THREAD

**Issue by RobinHoutevelts** [php-vcr/phpunit-testlistener-vcr#8]
Hi,

I noticed you merged PR https://github.com/php-vcr/phpunit-testlistener-vcr/pull/7 which enables us to use PhpUnit `5.1`.

However, you've not created a new tag release so packagist hasn't picked up your changes.
Doing a `composer update` doesn't update your package.

Could you create a new release and make sure packagist is up-to-date?

Regards,
Robin Houtevelts

**Comment by adri** [comment]
Whops sorry! Just released the version.
